# 数据库连接URL
spring.datasource.url: jdbc:mysql://${UJCMS_DB_HOST}:${UJCMS_DB_PORT:3306}/${UJCMS_DB_NAME}?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
# 数据库用户名
spring.datasource.username: ${UJCMS_DB_USER}
# 数据库密码
spring.datasource.password: ${UJCMS_DB_PASSWORD}
# 数据库驱动
spring.datasource.driver-class-name: ${UJCMS_DB_DRIVER:com.mysql.cj.jdbc.Driver}
# 执行初始化脚本的数据库类型
ujcms.data-sql-platform: ${UJCMS_DB_SQL_PLATFORM:mysql}
# 数据库类型（用于数据库备份）。支持 mysql、postgresql、kingbase、opengauss
ujcms.databaseType: ${UJCMS_DB_TYPE:mysql}

# 是否启用 Office 功能（商业版功能）
jodconverter.local.enabled: ${UJCMS_OFFICE_ENABLED:false}
# Office 安装路径
jodconverter.local.office-home: ${UJCMS_OFFICE_HOME:/opt/openoffice4}
