package com.ujcms.core.domain.base;

import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article";

    /**
     * 文章ID
     */
    @NotNull
    private Integer id = 0;

    /**
     * 站点ID
     */
    @NotNull
    private Integer siteId = 0;

    /**
     * 组织ID
     */
    @NotNull
    private Integer orgId = 0;

    /**
     * 栏目ID
     */
    @NotNull
    private Integer channelId = 0;

    /**
     * 创建用户ID
     */
    @NotNull
    private Integer userId = 0;

    /**
     * 修改用户ID
     */
    @Nullable
    private Integer modifiedUserId;

    /**
     * 发布日期
     */
    @NotNull
    private OffsetDateTime publishDate = OffsetDateTime.now();

    /**
     * 是否有图片
     */
    @NotNull
    private Boolean withImage = false;

    /**
     * 置顶
     */
    @NotNull
    private Short sticky = 0;

    /**
     * 状态(0:正常)
     */
    @NotNull
    private Short status = 0;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Nullable
    public Integer getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(@Nullable Integer modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    public OffsetDateTime getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(OffsetDateTime publishDate) {
        this.publishDate = publishDate;
    }

    public Boolean getWithImage() {
        return withImage;
    }

    public void setWithImage(Boolean withImage) {
        this.withImage = withImage;
    }

    public Short getSticky() {
        return sticky;
    }

    public void setSticky(Short sticky) {
        this.sticky = sticky;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }
}