package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleBufferBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article_buffer";

    /**
     * 文章ID
     */
    private int id = 0;

    /**
     * 评论次数
     */
    private int comments = 0;

    /**
     * 下载次数
     */
    private int downloads = 0;

    /**
     * 收藏次数
     */
    private int favorites = 0;

    /**
     * 顶
     */
    private int ups = 0;

    /**
     * 踩
     */
    private int downs = 0;

    /**
     * 浏览次数
     */
    private long views = 0;

    /**
     * 日浏览次数
     */
    private int dayViews = 0;

    /**
     * 周浏览次数
     */
    private int weekViews = 0;

    /**
     * 月浏览次数
     */
    private int monthViews = 0;

    /**
     * 季浏览次数
     */
    private int quarterViews = 0;

    /**
     * 年浏览次数
     */
    private long yearViews = 0;

    /**
     * 统计日
     */
    private int statDay = 0;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getComments() {
        return comments;
    }

    public void setComments(int comments) {
        this.comments = comments;
    }

    public int getDownloads() {
        return downloads;
    }

    public void setDownloads(int downloads) {
        this.downloads = downloads;
    }

    public int getFavorites() {
        return favorites;
    }

    public void setFavorites(int favorites) {
        this.favorites = favorites;
    }

    public int getUps() {
        return ups;
    }

    public void setUps(int ups) {
        this.ups = ups;
    }

    public int getDowns() {
        return downs;
    }

    public void setDowns(int downs) {
        this.downs = downs;
    }

    public long getViews() {
        return views;
    }

    public void setViews(long views) {
        this.views = views;
    }

    public int getDayViews() {
        return dayViews;
    }

    public void setDayViews(int dayViews) {
        this.dayViews = dayViews;
    }

    public int getWeekViews() {
        return weekViews;
    }

    public void setWeekViews(int weekViews) {
        this.weekViews = weekViews;
    }

    public int getMonthViews() {
        return monthViews;
    }

    public void setMonthViews(int monthViews) {
        this.monthViews = monthViews;
    }

    public int getQuarterViews() {
        return quarterViews;
    }

    public void setQuarterViews(int quarterViews) {
        this.quarterViews = quarterViews;
    }

    public long getYearViews() {
        return yearViews;
    }

    public void setYearViews(long yearViews) {
        this.yearViews = yearViews;
    }

    public int getStatDay() {
        return statDay;
    }

    public void setStatDay(int statDay) {
        this.statDay = statDay;
    }
}