package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleStatBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article_stat";

    /**
     * 文章ID
     */
    @NotNull
    private Integer articleId = 0;

    /**
     * 统计日
     */
    @NotNull
    private Integer statDay = 0;

    /**
     * 浏览次数
     */
    @NotNull
    private Integer views = 0;

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Integer getStatDay() {
        return statDay;
    }

    public void setStatDay(Integer statDay) {
        this.statDay = statDay;
    }

    public Integer getViews() {
        return views;
    }

    public void setViews(Integer views) {
        this.views = views;
    }
}