package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleFileBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article_file";

    /**
     * 文章ID
     */
    private int articleId = 0;

    /**
     * 文件名称
     */
    private String name = "";

    /**
     * 文件URL
     */
    private String url = "";

    /**
     * 文件大小
     */
    private long length = 0;

    /**
     * 排序
     */
    private short order = 32767;

    public int getArticleId() {
        return articleId;
    }

    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public long getLength() {
        return length;
    }

    public void setLength(long length) {
        this.length = length;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }
}