package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleFileBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article_file";

    /**
     * 文章ID
     */
    @NotNull
    private Integer articleId = 0;

    /**
     * 文件名称
     */
    @Length(max = 150)
    @NotNull
    private String name = "";

    /**
     * 文件URL
     */
    @Length(max = 255)
    @NotNull
    private String url = "";

    /**
     * 文件大小
     */
    @NotNull
    private Long length = 0L;

    /**
     * 排序
     */
    @NotNull
    private Short order = 32767;

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }
}