package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleImageBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article_image";

    /**
     * 文章ID
     */
    private int articleId = 0;

    /**
     * 图片URL
     */
    private String url = "";

    /**
     * 图片描述
     */
    private String description = "";

    /**
     * 排序
     */
    private short order = 32767;

    public int getArticleId() {
        return articleId;
    }

    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }
}