package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class AttachmentReferBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "attachment_refer";

    /**
     * 附件ID
     */
    @NotNull
    private Integer attachmentId = 0;

    /**
     * 引用类型
     */
    @Length(max = 20)
    @NotNull
    private String referType = "";

    /**
     * 引用ID
     */
    @NotNull
    private Integer referId = 0;

    public Integer getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getReferType() {
        return referType;
    }

    public void setReferType(String referType) {
        this.referType = referType;
    }

    public Integer getReferId() {
        return referId;
    }

    public void setReferId(Integer referId) {
        this.referId = referId;
    }
}