package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class AttachmentReferBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "attachment_refer";

    /**
     * 附件ID
     */
    private int attachmentId = 0;

    /**
     * 引用类型
     */
    private String referType = "";

    /**
     * 引用ID
     */
    private int referId = 0;

    public int getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(int attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getReferType() {
        return referType;
    }

    public void setReferType(String referType) {
        this.referType = referType;
    }

    public int getReferId() {
        return referId;
    }

    public void setReferId(int referId) {
        this.referId = referId;
    }
}