package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block";

    /**
     * 区块ID
     */
    @NotNull
    private Integer id = 0;

    /**
     * 站点ID
     */
    @NotNull
    private Integer siteId = 0;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    private String name = "";

    /**
     * 别名
     */
    @Length(max = 50)
    @NotNull
    private String alias = "";

    /**
     * 共享范围(0:本站私有,1:子站点共享,2:全局共享)
     */
    @NotNull
    private Short scope = 0;

    /**
     * 是否有摘要
     */
    @NotNull
    private Boolean withDescription = false;

    /**
     * 是否有图片
     */
    @NotNull
    private Boolean withImage = false;

    /**
     * 图片宽度
     */
    @NotNull
    private Integer imageWidth = 300;

    /**
     * 图片高度
     */
    @NotNull
    private Integer imageHeight = 200;

    /**
     * 是否有手机端图片
     */
    @NotNull
    private Boolean withMobileImage = false;

    /**
     * 手机端图片宽度
     */
    @NotNull
    private Integer mobileImageWidth = 300;

    /**
     * 手机端图片高度
     */
    @NotNull
    private Integer mobileImageHeight = 200;

    /**
     * 是否启用
     */
    @NotNull
    private Boolean enabled = true;

    /**
     * 排序
     */
    @NotNull
    private Short order = 32767;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Short getScope() {
        return scope;
    }

    public void setScope(Short scope) {
        this.scope = scope;
    }

    public Boolean getWithDescription() {
        return withDescription;
    }

    public void setWithDescription(Boolean withDescription) {
        this.withDescription = withDescription;
    }

    public Boolean getWithImage() {
        return withImage;
    }

    public void setWithImage(Boolean withImage) {
        this.withImage = withImage;
    }

    public Integer getImageWidth() {
        return imageWidth;
    }

    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    public Integer getImageHeight() {
        return imageHeight;
    }

    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

    public Boolean getWithMobileImage() {
        return withMobileImage;
    }

    public void setWithMobileImage(Boolean withMobileImage) {
        this.withMobileImage = withMobileImage;
    }

    public Integer getMobileImageWidth() {
        return mobileImageWidth;
    }

    public void setMobileImageWidth(Integer mobileImageWidth) {
        this.mobileImageWidth = mobileImageWidth;
    }

    public Integer getMobileImageHeight() {
        return mobileImageHeight;
    }

    public void setMobileImageHeight(Integer mobileImageHeight) {
        this.mobileImageHeight = mobileImageHeight;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }
}