package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockItemBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block_item";

    /**
     * 区块项ID
     */
    @NotNull
    private Integer id = 0;

    /**
     * 站点ID
     */
    @NotNull
    private Integer siteId = 0;

    /**
     * 区块ID
     */
    @NotNull
    private Integer blockId = 0;

    /**
     * 文章ID
     */
    @Nullable
    private Integer articleId;

    /**
     * 标题
     */
    @Length(max = 150)
    @NotNull
    private String title = "";

    /**
     * 描述
     */
    @Length(max = 1000)
    @Nullable
    private String description;

    /**
     * 链接
     */
    @Length(max = 255)
    @Nullable
    private String linkUrl;

    /**
     * 图片
     */
    @Length(max = 255)
    @Nullable
    private String image;

    /**
     * 手机端图片
     */
    @Length(max = 255)
    @Nullable
    private String mobileImage;

    /**
     * 是否启用
     */
    @NotNull
    private Boolean enabled = true;

    /**
     * 排序
     */
    @NotNull
    private Short order = 32767;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Integer getBlockId() {
        return blockId;
    }

    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    @Nullable
    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(@Nullable Integer articleId) {
        this.articleId = articleId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @Nullable
    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(@Nullable String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Nullable
    public String getImage() {
        return image;
    }

    public void setImage(@Nullable String image) {
        this.image = image;
    }

    @Nullable
    public String getMobileImage() {
        return mobileImage;
    }

    public void setMobileImage(@Nullable String mobileImage) {
        this.mobileImage = mobileImage;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }
}