package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block";

    /**
     * 区块ID
     */
    private int id = 0;

    /**
     * 站点ID
     */
    private int siteId = 0;

    /**
     * 名称
     */
    private String name = "";

    /**
     * 别名
     */
    private String alias = "";

    /**
     * 共享范围(0:本站私有,1:子站点共享,2:全局共享)
     */
    private short scope = 0;

    /**
     * 是否有摘要
     */
    private boolean withDescription = false;

    /**
     * 是否有图片
     */
    private boolean withImage = false;

    /**
     * 图片宽度
     */
    private int imageWidth = 300;

    /**
     * 图片高度
     */
    private int imageHeight = 200;

    /**
     * 是否有手机端图片
     */
    private boolean withMobileImage;

    /**
     * 手机端图片宽度
     */
    private int mobileImageWidth = 300;

    /**
     * 手机端图片高度
     */
    private int mobileImageHeight = 200;

    /**
     * 是否启用
     */
    private boolean enabled = true;

    /**
     * 排序
     */
    private short order = 32767;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSiteId() {
        return siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public short getScope() {
        return scope;
    }

    public void setScope(short scope) {
        this.scope = scope;
    }

    public boolean isWithDescription() {
        return withDescription;
    }

    public void setWithDescription(boolean withDescription) {
        this.withDescription = withDescription;
    }

    public boolean isWithImage() {
        return withImage;
    }

    public void setWithImage(boolean withImage) {
        this.withImage = withImage;
    }

    public int getImageWidth() {
        return imageWidth;
    }

    public void setImageWidth(int imageWidth) {
        this.imageWidth = imageWidth;
    }

    public int getImageHeight() {
        return imageHeight;
    }

    public void setImageHeight(int imageHeight) {
        this.imageHeight = imageHeight;
    }

    public boolean isWithMobileImage() {
        return withMobileImage;
    }

    public void setWithMobileImage(boolean withMobileImage) {
        this.withMobileImage = withMobileImage;
    }

    public int getMobileImageWidth() {
        return mobileImageWidth;
    }

    public void setMobileImageWidth(int mobileImageWidth) {
        this.mobileImageWidth = mobileImageWidth;
    }

    public int getMobileImageHeight() {
        return mobileImageHeight;
    }

    public void setMobileImageHeight(int mobileImageHeight) {
        this.mobileImageHeight = mobileImageHeight;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }
}