package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockItemBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block_item";

    /**
     * 区块项ID
     */
    private int id = 0;

    /**
     * 站点ID
     */
    private int siteId = 0;

    /**
     * 区块ID
     */
    private int blockId = 0;

    /**
     * 文章ID
     */
    @Nullable
    private Integer articleId;

    /**
     * 标题
     */
    @Nullable
    private String title;

    /**
     * 描述
     */
    @Nullable
    private String description;

    /**
     * 链接
     */
    @Nullable
    private String linkUrl;

    /**
     * 图片
     */
    @Nullable
    private String image;

    /**
     * 手机端图片
     */
    @Nullable
    private String mobileImage;

    /**
     * 是否启用
     */
    private boolean enabled = true;

    /**
     * 排序
     */
    private short order = 32767;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSiteId() {
        return siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    public int getBlockId() {
        return blockId;
    }

    public void setBlockId(int blockId) {
        this.blockId = blockId;
    }

    @Nullable
    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(@Nullable Integer articleId) {
        this.articleId = articleId;
    }

    @Nullable
    public String getTitle() {
        return title;
    }

    public void setTitle(@Nullable String title) {
        this.title = title;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @Nullable
    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(@Nullable String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Nullable
    public String getImage() {
        return image;
    }

    public void setImage(@Nullable String image) {
        this.image = image;
    }

    @Nullable
    public String getMobileImage() {
        return mobileImage;
    }

    public void setMobileImage(@Nullable String mobileImage) {
        this.mobileImage = mobileImage;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }
}