package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ChannelExtBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "channel_ext";

    /**
     * 栏目ID
     */
    private int id = 0;

    /**
     * SEO标题
     */
    @Nullable
    private String seoTitle;

    /**
     * SEO关键词
     */
    @Nullable
    private String seoKeywords;

    /**
     * SEO描述
     */
    @Nullable
    private String seoDescription;

    /**
     * 文章模板
     */
    @Nullable
    private String articleTemplate;

    /**
     * 栏目模板
     */
    @Nullable
    private String channelTemplate;

    /**
     * 每页条数
     */
    private short pageSize = 20;

    /**
     * 图片
     */
    @Nullable
    private String image;

    /**
     * 转向链接地址
     */
    @Nullable
    private String linkUrl;

    /**
     * 是否新窗口打开
     */
    private boolean targetBlank = false;

    /**
     * 是否允许评论
     */
    private boolean allowComment = true;

    /**
     * 是否允许投稿
     */
    private boolean allowContribute = false;

    /**
     * 是否允许搜索
     */
    private boolean allowSearch = true;

    /**
     * 静态页文件
     */
    @Nullable
    private String staticFile;

    /**
     * 手机端静态页文件
     */
    @Nullable
    private String mobileStaticFile;

    /**
     * 正文
     */
    @Nullable
    private String text;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Nullable
    public String getSeoTitle() {
        return seoTitle;
    }

    public void setSeoTitle(@Nullable String seoTitle) {
        this.seoTitle = seoTitle;
    }

    @Nullable
    public String getSeoKeywords() {
        return seoKeywords;
    }

    public void setSeoKeywords(@Nullable String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    @Nullable
    public String getSeoDescription() {
        return seoDescription;
    }

    public void setSeoDescription(@Nullable String seoDescription) {
        this.seoDescription = seoDescription;
    }

    @Nullable
    public String getArticleTemplate() {
        return articleTemplate;
    }

    public void setArticleTemplate(@Nullable String articleTemplate) {
        this.articleTemplate = articleTemplate;
    }

    @Nullable
    public String getChannelTemplate() {
        return channelTemplate;
    }

    public void setChannelTemplate(@Nullable String channelTemplate) {
        this.channelTemplate = channelTemplate;
    }

    public short getPageSize() {
        return pageSize;
    }

    public void setPageSize(short pageSize) {
        this.pageSize = pageSize;
    }

    @Nullable
    public String getImage() {
        return image;
    }

    public void setImage(@Nullable String image) {
        this.image = image;
    }

    @Nullable
    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(@Nullable String linkUrl) {
        this.linkUrl = linkUrl;
    }

    public boolean isTargetBlank() {
        return targetBlank;
    }

    public void setTargetBlank(boolean targetBlank) {
        this.targetBlank = targetBlank;
    }

    public boolean isAllowComment() {
        return allowComment;
    }

    public void setAllowComment(boolean allowComment) {
        this.allowComment = allowComment;
    }

    public boolean isAllowContribute() {
        return allowContribute;
    }

    public void setAllowContribute(boolean allowContribute) {
        this.allowContribute = allowContribute;
    }

    public boolean isAllowSearch() {
        return allowSearch;
    }

    public void setAllowSearch(boolean allowSearch) {
        this.allowSearch = allowSearch;
    }

    @Nullable
    public String getStaticFile() {
        return staticFile;
    }

    public void setStaticFile(@Nullable String staticFile) {
        this.staticFile = staticFile;
    }

    @Nullable
    public String getMobileStaticFile() {
        return mobileStaticFile;
    }

    public void setMobileStaticFile(@Nullable String mobileStaticFile) {
        this.mobileStaticFile = mobileStaticFile;
    }

    @Nullable
    public String getText() {
        return text;
    }

    public void setText(@Nullable String text) {
        this.text = text;
    }
}