package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ChannelGroupBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "channel_group";

    /**
     * 栏目ID
     */
    @NotNull
    private Integer channelId = 0;

    /**
     * 用户组ID
     */
    @NotNull
    private Integer groupId = 0;

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}