package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ChannelGroupBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "channel_group";

    /**
     * 用户组ID
     */
    private int groupId = 0;

    /**
     * 栏目ID
     */
    private int channelId = 0;

    public int getGroupId() {
        return groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    public int getChannelId() {
        return channelId;
    }

    public void setChannelId(int channelId) {
        this.channelId = channelId;
    }
}