package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class DictBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "dict";

    /**
     * 字典ID
     */
    private int id = 0;

    /**
     * 数据字典类型ID
     */
    private int typeId = 0;

    /**
     * 上级ID
     */
    @Nullable
    private Integer parentId;

    /**
     * 名称
     */
    private String name = "";

    /**
     * 值
     */
    private String value = "";

    /**
     * 备注
     */
    @Nullable
    private String remark;

    /**
     * 排列顺序
     */
    private short order = 32767;

    /**
     * 是否启用
     */
    private boolean enabled = true;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    @Nullable
    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(@Nullable Integer parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Nullable
    public String getRemark() {
        return remark;
    }

    public void setRemark(@Nullable String remark) {
        this.remark = remark;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}