package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class GlobalBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "global";

    /**
     * ID
     */
    private int id = 0;

    /**
     * 上下文路径
     */
    @Nullable
    private String contextPath;

    /**
     * 端口号
     */
    @Nullable
    private Integer port;

    /**
     * 默认站点ID
     */
    private int defaultSiteId = 0;

    /**
     * 栏目URL地址
     */
    @Nullable
    private String channelUrl;

    /**
     * 文章URL地址
     */
    @Nullable
    private String articleUrl;

    /**
     * 上传设置
     */
    @Nullable
    private String uploadSettings;

    /**
     * 注册设置
     */
    @Nullable
    private String registerSettings;

    /**
     * 邮件设置
     */
    @Nullable
    private String emailSettings;

    /**
     * 自定义设置
     */
    @Nullable
    private String customsSettings;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Nullable
    public String getContextPath() {
        return contextPath;
    }

    public void setContextPath(@Nullable String contextPath) {
        this.contextPath = contextPath;
    }

    @Nullable
    public Integer getPort() {
        return port;
    }

    public void setPort(@Nullable Integer port) {
        this.port = port;
    }

    public int getDefaultSiteId() {
        return defaultSiteId;
    }

    public void setDefaultSiteId(int defaultSiteId) {
        this.defaultSiteId = defaultSiteId;
    }

    @Nullable
    public String getChannelUrl() {
        return channelUrl;
    }

    public void setChannelUrl(@Nullable String channelUrl) {
        this.channelUrl = channelUrl;
    }

    @Nullable
    public String getArticleUrl() {
        return articleUrl;
    }

    public void setArticleUrl(@Nullable String articleUrl) {
        this.articleUrl = articleUrl;
    }

    @Nullable
    public String getUploadSettings() {
        return uploadSettings;
    }

    public void setUploadSettings(@Nullable String uploadSettings) {
        this.uploadSettings = uploadSettings;
    }

    @Nullable
    public String getRegisterSettings() {
        return registerSettings;
    }

    public void setRegisterSettings(@Nullable String registerSettings) {
        this.registerSettings = registerSettings;
    }

    @Nullable
    public String getEmailSettings() {
        return emailSettings;
    }

    public void setEmailSettings(@Nullable String emailSettings) {
        this.emailSettings = emailSettings;
    }

    @Nullable
    public String getCustomsSettings() {
        return customsSettings;
    }

    public void setCustomsSettings(@Nullable String customsSettings) {
        this.customsSettings = customsSettings;
    }
}