package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ModelBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "model";

    /**
     * 模型ID
     */
    private int id = 0;

    /**
     * 站点ID
     */
    @Nullable
    private Integer siteId;

    /**
     * 名称
     */
    private String name = "";

    /**
     * 类型(,article:文章,channel:栏目,user:用户,site:站点设置,global:全局设置)
     */
    private String type = "";

    /**
     * 共享范围(0:本站私有,1:子站点共享,2:全局共享)
     */
    private short scope = 0;

    /**
     * 排列顺序
     */
    private short order = 32767;

    /**
     * 主字段集
     */
    @Nullable
    private String mains;

    /**
     * 右侧字段集
     */
    @Nullable
    private String asides;

    /**
     * 自定义字段集
     */
    @Nullable
    private String customs;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Nullable
    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(@Nullable Integer siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public short getScope() {
        return scope;
    }

    public void setScope(short scope) {
        this.scope = scope;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }

    @Nullable
    public String getMains() {
        return mains;
    }

    public void setMains(@Nullable String mains) {
        this.mains = mains;
    }

    @Nullable
    public String getAsides() {
        return asides;
    }

    public void setAsides(@Nullable String asides) {
        this.asides = asides;
    }

    @Nullable
    public String getCustoms() {
        return customs;
    }

    public void setCustoms(@Nullable String customs) {
        this.customs = customs;
    }
}