package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class OrgBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "org";

    /**
     * 组织ID
     */
    private int id = 0;

    /**
     * 上级组织ID
     */
    @Nullable
    private Integer parentId;

    /**
     * 名称
     */
    private String name = "";

    /**
     * 电话
     */
    @Nullable
    private String phone;

    /**
     * 地址
     */
    @Nullable
    private String address;

    /**
     * 联系人
     */
    @Nullable
    private String contacts;

    /**
     * 层级
     */
    private short depth = 1;

    /**
     * 排序
     */
    private short order = 32767;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Nullable
    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(@Nullable Integer parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    public String getPhone() {
        return phone;
    }

    public void setPhone(@Nullable String phone) {
        this.phone = phone;
    }

    @Nullable
    public String getAddress() {
        return address;
    }

    public void setAddress(@Nullable String address) {
        this.address = address;
    }

    @Nullable
    public String getContacts() {
        return contacts;
    }

    public void setContacts(@Nullable String contacts) {
        this.contacts = contacts;
    }

    public short getDepth() {
        return depth;
    }

    public void setDepth(short depth) {
        this.depth = depth;
    }

    public short getOrder() {
        return order;
    }

    public void setOrder(short order) {
        this.order = order;
    }
}