package com.ujcms.core.domain.base;



/**
 * This class was generated by MyBatis Generator.
 */
public class SeqBase {

    private String name = "";


    private long nextVal = 1;


    private int cacheSize = 0;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getNextVal() {
        return nextVal;
    }

    public void setNextVal(long nextVal) {
        this.nextVal = nextVal;
    }

    public int getCacheSize() {
        return cacheSize;
    }

    public void setCacheSize(int cacheSize) {
        this.cacheSize = cacheSize;
    }
}