package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SiteBufferBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "site_buffer";

    /**
     * 站点ID
     */
    @NotNull
    private Integer id = 0;

    /**
     * 浏览次数
     */
    @NotNull
    private Long views = 0L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getViews() {
        return views;
    }

    public void setViews(Long views) {
        this.views = views;
    }
}