package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SiteTreeBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "site_tree";

    /**
     * 祖先ID
     */
    @NotNull
    private Integer ancestorId = 0;

    /**
     * 后代ID
     */
    @NotNull
    private Integer descendantId = 0;

    public Integer getAncestorId() {
        return ancestorId;
    }

    public void setAncestorId(Integer ancestorId) {
        this.ancestorId = ancestorId;
    }

    public Integer getDescendantId() {
        return descendantId;
    }

    public void setDescendantId(Integer descendantId) {
        this.descendantId = descendantId;
    }
}