package com.ujcms.core.domain.base;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SiteTreeBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "site_tree";

    /**
     * 祖先ID
     */
    private int ancestorId = 0;

    /**
     * 后代ID
     */
    private int descendantId = 0;

    public int getAncestorId() {
        return ancestorId;
    }

    public void setAncestorId(int ancestorId) {
        this.ancestorId = ancestorId;
    }

    public int getDescendantId() {
        return descendantId;
    }

    public void setDescendantId(int descendantId) {
        this.descendantId = descendantId;
    }
}