package com.ujcms.core.domain.base;

import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SiteCustomBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "site_custom";

    /**
     * 站点ID
     */
    private int siteId = 0;

    /**
     * 名称
     */
    private String name = "";

    /**
     * 值
     */
    @Nullable
    private String value;

    public int getSiteId() {
        return siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    public String getValue() {
        return value;
    }

    public void setValue(@Nullable String value) {
        this.value = value;
    }
}