package com.ujcms.core.domain.base;


import org.springframework.lang.Nullable;

import java.time.OffsetDateTime;

/**
 * This class was generated by MyBatis Generator.
 */
public class UserDetailBase {
    /**
     * 用户ID
     */

    private int id = 0;

    /**
     * 创建时间
     */

    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 真实姓名
     */
    @Nullable

    private String realName;

    /**
     * 性别(m:男,f:女,n:保密)
     */
    @Nullable

    private String gender;

    /**
     * 出生日期
     */
    @Nullable

    private OffsetDateTime birthday;

    /**
     * 居住地
     */
    @Nullable

    private String location;

    /**
     * 自我介绍
     */
    @Nullable

    private String bio;

    /**
     * 最后登录时间
     */

    private OffsetDateTime loginDate = OffsetDateTime.now();

    /**
     * 最后登录IP
     */

    private String loginIp = "localhost";

    /**
     * 登录次数
     */

    private int loginCount = 0;

    /**
     * 等级
     */

    private short rank = 999;

    /**
     * 是否禁用
     */

    private boolean disabled = false;

    /**
     * 是否导航菜单
     */

    private boolean nav4 = true;

    @Nullable
    private Boolean published = true;

    /**
     * 正文
     */
    @Nullable

    private String text;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "ujcms_user_detail";

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    @Nullable
    public String getRealName() {
        return realName;
    }

    public void setRealName(@Nullable String realName) {
        this.realName = realName;
    }

    @Nullable
    public String getGender() {
        return gender;
    }

    public void setGender(@Nullable String gender) {
        this.gender = gender;
    }

    @Nullable
    public OffsetDateTime getBirthday() {
        return birthday;
    }

    public void setBirthday(@Nullable OffsetDateTime birthday) {
        this.birthday = birthday;
    }

    @Nullable
    public String getLocation() {
        return location;
    }

    public void setLocation(@Nullable String location) {
        this.location = location;
    }

    @Nullable
    public String getBio() {
        return bio;
    }

    public void setBio(@Nullable String bio) {
        this.bio = bio;
    }

    public OffsetDateTime getLoginDate() {
        return loginDate;
    }

    public void setLoginDate(OffsetDateTime loginDate) {
        this.loginDate = loginDate;
    }

    public String getLoginIp() {
        return loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public int getLoginCount() {
        return loginCount;
    }

    public void setLoginCount(int loginCount) {
        this.loginCount = loginCount;
    }

    public short getRank() {
        return rank;
    }

    public void setRank(short rank) {
        this.rank = rank;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    public boolean isNav4() {
        return nav4;
    }

    public void setNav4(boolean nav4) {
        this.nav4 = nav4;
    }

    @Nullable
    public Boolean getPublished() {
        return published;
    }

    public void setPublished(@Nullable Boolean published) {
        this.published = published;
    }

    @Nullable
    public String getText() {
        return text;
    }

    public void setText(@Nullable String text) {
        this.text = text;
    }
}