package com.ujcms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class UserRoleBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "user_role";

    /**
     * 用户ID
     */
    @NotNull
    private Integer userId = 0;

    /**
     * 角色ID
     */
    @NotNull
    private Integer roleId = 0;

    /**
     * 角色排序
     */
    @NotNull
    private Short order = 9999;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }
}