package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ActionBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "action";

    /**
     * 动作ID
     */
    @NotNull
    @Schema(description="动作ID")
    private Long id = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 用户ID
     */
    @Nullable
    @Schema(description="用户ID")
    private Long userId;

    /**
     * IP
     */
    @Length(max = 45)
    @Nullable
    @Schema(description="IP")
    private String ip;

    /**
     * Cookie
     */
    @Nullable
    @Schema(description="Cookie")
    private Long cookie;

    /**
     * 动作对象类型
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="动作对象类型")
    private String refType = "";

    /**
     * 动作对象ID
     */
    @NotNull
    @Schema(description="动作对象ID")
    private Long refId = 0L;

    /**
     * 动作选项
     */
    @Length(max = 255)
    @NotNull
    @Schema(description="动作选项")
    private String refOption = "";

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    @Nullable
    public Long getUserId() {
        return userId;
    }

    public void setUserId(@Nullable Long userId) {
        this.userId = userId;
    }

    @Nullable
    public String getIp() {
        return ip;
    }

    public void setIp(@Nullable String ip) {
        this.ip = ip;
    }

    @Nullable
    public Long getCookie() {
        return cookie;
    }

    public void setCookie(@Nullable Long cookie) {
        this.cookie = cookie;
    }

    public String getRefType() {
        return refType;
    }

    public void setRefType(String refType) {
        this.refType = refType;
    }

    public Long getRefId() {
        return refId;
    }

    public void setRefId(Long refId) {
        this.refId = refId;
    }

    public String getRefOption() {
        return refOption;
    }

    public void setRefOption(String refOption) {
        this.refOption = refOption;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }
}