package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ArticleBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "article";

    /**
     * 文章ID
     */
    @NotNull
    @Schema(description="文章ID")
    private Long id = 0L;

    /**
     * 源文章ID
     */
    @Nullable
    @Schema(description="源文章ID")
    private Long srcId;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 组织ID
     */
    @NotNull
    @Schema(description="组织ID")
    private Long orgId = 0L;

    /**
     * 栏目ID
     */
    @NotNull
    @Schema(description="栏目ID")
    private Long channelId = 0L;

    /**
     * 创建用户ID
     */
    @NotNull
    @Schema(description="创建用户ID")
    private Long userId = 0L;

    /**
     * 修改用户ID
     */
    @NotNull
    @Schema(description="修改用户ID")
    private Long modifiedUserId = 0L;

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 修改日期
     */
    @NotNull
    @Schema(description="修改日期")
    private OffsetDateTime modified = OffsetDateTime.now();

    /**
     * 发布日期
     */
    @NotNull
    @Schema(description="发布日期")
    private OffsetDateTime publishDate = OffsetDateTime.now();

    /**
     * 上线日期
     */
    @Nullable
    @Schema(description="上线日期")
    private OffsetDateTime onlineDate;

    /**
     * 下线日期
     */
    @Nullable
    @Schema(description="下线日期")
    private OffsetDateTime offlineDate;

    /**
     * 置顶
     */
    @NotNull
    @Schema(description="置顶")
    private Short sticky = 0;

    /**
     * 置顶时间
     */
    @Nullable
    @Schema(description="置顶时间")
    private OffsetDateTime stickyDate;

    /**
     * 是否有图片
     */
    @NotNull
    @Schema(description="是否有图片")
    private Boolean withImage = false;

    /**
     * 录入类型(0:常规,1:投稿,2:采集,3:接口,4:站内推送,5:站群推送)
     */
    @NotNull
    @Schema(description="录入类型(0:常规,1:投稿,2:采集,3:接口,4:站内推送,5:站群推送)")
    private Short inputType = 0;

    /**
     * 类型(0:常规,1:复制,2:映射,3:引用)
     */
    @NotNull
    @Schema(description="类型(0:常规,1:复制,2:映射,3:引用)")
    private Short type = 0;

    /**
     * 状态(0:已发布,1:已归档,5:待发布,10:草稿,11:待审核,12:审核中,20:已删除,21:已下线,22:已退回)
     */
    @NotNull
    @Schema(description="状态(0:已发布,1:已归档,5:待发布,10:草稿,11:待审核,12:审核中,20:已删除,21:已下线,22:已退回)")
    private Short status = 0;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Long order = 0L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Nullable
    public Long getSrcId() {
        return srcId;
    }

    public void setSrcId(@Nullable Long srcId) {
        this.srcId = srcId;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public OffsetDateTime getModified() {
        return modified;
    }

    public void setModified(OffsetDateTime modified) {
        this.modified = modified;
    }

    public OffsetDateTime getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(OffsetDateTime publishDate) {
        this.publishDate = publishDate;
    }

    @Nullable
    public OffsetDateTime getOnlineDate() {
        return onlineDate;
    }

    public void setOnlineDate(@Nullable OffsetDateTime onlineDate) {
        this.onlineDate = onlineDate;
    }

    @Nullable
    public OffsetDateTime getOfflineDate() {
        return offlineDate;
    }

    public void setOfflineDate(@Nullable OffsetDateTime offlineDate) {
        this.offlineDate = offlineDate;
    }

    public Short getSticky() {
        return sticky;
    }

    public void setSticky(Short sticky) {
        this.sticky = sticky;
    }

    @Nullable
    public OffsetDateTime getStickyDate() {
        return stickyDate;
    }

    public void setStickyDate(@Nullable OffsetDateTime stickyDate) {
        this.stickyDate = stickyDate;
    }

    public Boolean getWithImage() {
        return withImage;
    }

    public void setWithImage(Boolean withImage) {
        this.withImage = withImage;
    }

    public Short getInputType() {
        return inputType;
    }

    public void setInputType(Short inputType) {
        this.inputType = inputType;
    }

    public Short getType() {
        return type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }
}