package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class AttachmentReferBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "attachment_refer";

    /**
     * 附件引用ID
     */
    @NotNull
    @Schema(description="附件引用ID")
    private Long id = 0L;

    /**
     * 附件ID
     */
    @NotNull
    @Schema(description="附件ID")
    private Long attachmentId = 0L;

    /**
     * 引用类型
     */
    @Length(max = 20)
    @NotNull
    @Schema(description="引用类型")
    private String referType = "";

    /**
     * 引用ID
     */
    @NotNull
    @Schema(description="引用ID")
    private Long referId = 0L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getReferType() {
        return referType;
    }

    public void setReferType(String referType) {
        this.referType = referType;
    }

    public Long getReferId() {
        return referId;
    }

    public void setReferId(Long referId) {
        this.referId = referId;
    }
}