package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockItemBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block_item";

    /**
     * 区块项ID
     */
    @NotNull
    @Schema(description="区块项ID")
    private Long id = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 区块ID
     */
    @NotNull
    @Schema(description="区块ID")
    private Long blockId = 0L;

    /**
     * 文章ID
     */
    @Nullable
    @Schema(description="文章ID")
    private Long articleId;

    /**
     * 标题
     */
    @Length(max = 150)
    @NotNull
    @Schema(description="标题")
    private String title = "";

    /**
     * 副标题
     */
    @Length(max = 150)
    @Nullable
    @Schema(description="副标题")
    private String subtitle;

    /**
     * 描述
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="描述")
    private String description;

    /**
     * 链接
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="链接")
    private String linkUrl;

    /**
     * 图片
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="图片")
    private String image;

    /**
     * 手机端图片
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="手机端图片")
    private String mobileImage;

    /**
     * 视频
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="视频")
    private String video;

    /**
     * 是否新窗口打开
     */
    @NotNull
    @Schema(description="是否新窗口打开")
    private Boolean targetBlank = false;

    /**
     * 是否启用
     */
    @NotNull
    @Schema(description="是否启用")
    private Boolean enabled = true;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Long order = 0L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getBlockId() {
        return blockId;
    }

    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    @Nullable
    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(@Nullable Long articleId) {
        this.articleId = articleId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Nullable
    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(@Nullable String subtitle) {
        this.subtitle = subtitle;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @Nullable
    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(@Nullable String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Nullable
    public String getImage() {
        return image;
    }

    public void setImage(@Nullable String image) {
        this.image = image;
    }

    @Nullable
    public String getMobileImage() {
        return mobileImage;
    }

    public void setMobileImage(@Nullable String mobileImage) {
        this.mobileImage = mobileImage;
    }

    @Nullable
    public String getVideo() {
        return video;
    }

    public void setVideo(@Nullable String video) {
        this.video = video;
    }

    public Boolean getTargetBlank() {
        return targetBlank;
    }

    public void setTargetBlank(Boolean targetBlank) {
        this.targetBlank = targetBlank;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }
}