package com.ujcms.cms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class ChannelRoleBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "channel_role";

    /**
     * 栏目ID
     */
    @NotNull
    private Integer channelId = 0;

    /**
     * 角色ID
     */
    @NotNull
    private Integer roleId = 0;

    /**
     * 站点ID
     */
    @NotNull
    private Integer siteId = 0;

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
}