package com.ujcms.cms.core.domain.base;

import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class GroupAccessBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "group_access";

    /**
     * 用户组ID
     */
    @NotNull
    private Integer groupId = 0;

    /**
     * 栏目ID
     */
    @NotNull
    private Integer channelId = 0;

    /**
     * 站点ID
     */
    @NotNull
    private Integer siteId = 0;

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
}