package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class OperationLogExtBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "operation_log_ext";

    /**
     * 操作日志扩展ID
     */
    @NotNull
    @Schema(description="操作日志扩展ID")
    private Long id = 0L;

    /**
     * 请求URL
     */
    @Nullable
    @Schema(description="请求URL")
    private String requestUrl;

    /**
     * 请求体
     */
    @Nullable
    @Schema(description="请求体")
    private String requestBody;

    /**
     * 响应体
     */
    @Nullable
    @Schema(description="响应体")
    private String responseEntity;

    /**
     * 异常堆栈
     */
    @Nullable
    @Schema(description="异常堆栈")
    private String exceptionStack;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Nullable
    public String getRequestUrl() {
        return requestUrl;
    }

    public void setRequestUrl(@Nullable String requestUrl) {
        this.requestUrl = requestUrl;
    }

    @Nullable
    public String getRequestBody() {
        return requestBody;
    }

    public void setRequestBody(@Nullable String requestBody) {
        this.requestBody = requestBody;
    }

    @Nullable
    public String getResponseEntity() {
        return responseEntity;
    }

    public void setResponseEntity(@Nullable String responseEntity) {
        this.responseEntity = responseEntity;
    }

    @Nullable
    public String getExceptionStack() {
        return exceptionStack;
    }

    public void setExceptionStack(@Nullable String exceptionStack) {
        this.exceptionStack = exceptionStack;
    }
}