package com.ujcms.cms.core.domain.base;

import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class RoleBase {
    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "role";

    /**
     * 角色ID
     */
    @NotNull
    private Integer id = 0;

    /**
     * 站点ID
     */
    @Nullable
    private Integer siteId;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    private String name = "";

    /**
     * 描述
     */
    @Length(max = 300)
    @Nullable
    private String description;

    /**
     * 全局数据权限
     */
    @NotNull
    private Boolean globalPermission = false;

    /**
     * 所有文章权限
     */
    @NotNull
    private Boolean allArticlePermission = false;

    /**
     * 数据权限范围(1:所有,2:本组织,3:自身)
     */
    @NotNull
    private Short dataScope = 1;

    /**
     * 等级
     */
    @NotNull
    private Short rank = 32767;

    /**
     * 类型(1:系统管理员,2:安全管理员,3:审计管理员,4:常规角色)
     */
    @NotNull
    private Short type = 4;

    /**
     * 共享范围(0:本站私有,1:子站点共享,2:全局共享)
     */
    @NotNull
    private Short scope = 0;

    /**
     * 排序
     */
    @NotNull
    private Short order = 32767;

    /**
     * 所有功能权限
     */
    @NotNull
    private Boolean allPermission = false;

    /**
     * 所有授权权限
     */
    @NotNull
    private Boolean allGrantPermission = true;

    /**
     * 功能权限
     */
    @Nullable
    private String permission;

    /**
     * 授权权限
     */
    @Nullable
    private String grantPermission;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Nullable
    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(@Nullable Integer siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    public Boolean getGlobalPermission() {
        return globalPermission;
    }

    public void setGlobalPermission(Boolean globalPermission) {
        this.globalPermission = globalPermission;
    }

    public Boolean getAllArticlePermission() {
        return allArticlePermission;
    }

    public void setAllArticlePermission(Boolean allArticlePermission) {
        this.allArticlePermission = allArticlePermission;
    }

    public Short getDataScope() {
        return dataScope;
    }

    public void setDataScope(Short dataScope) {
        this.dataScope = dataScope;
    }

    public Short getRank() {
        return rank;
    }

    public void setRank(Short rank) {
        this.rank = rank;
    }

    public Short getType() {
        return type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public Short getScope() {
        return scope;
    }

    public void setScope(Short scope) {
        this.scope = scope;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }

    public Boolean getAllPermission() {
        return allPermission;
    }

    public void setAllPermission(Boolean allPermission) {
        this.allPermission = allPermission;
    }

    public Boolean getAllGrantPermission() {
        return allGrantPermission;
    }

    public void setAllGrantPermission(Boolean allGrantPermission) {
        this.allGrantPermission = allGrantPermission;
    }

    @Nullable
    public String getPermission() {
        return permission;
    }

    public void setPermission(@Nullable String permission) {
        this.permission = permission;
    }

    @Nullable
    public String getGrantPermission() {
        return grantPermission;
    }

    public void setGrantPermission(@Nullable String grantPermission) {
        this.grantPermission = grantPermission;
    }
}