package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SiteBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "site";

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long id = 0L;

    /**
     * 上级站点ID
     */
    @Nullable
    @Schema(description="上级站点ID")
    private Long parentId;

    /**
     * 组织ID
     */
    @NotNull
    @Schema(description="组织ID")
    private Long orgId = 0L;

    /**
     * 模型ID
     */
    @NotNull
    @Schema(description="模型ID")
    private Long modelId = 0L;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="名称")
    private String name = "";

    /**
     * 描述
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="描述")
    private String description;

    /**
     * 协议(http,https)
     */
    @Length(max = 20)
    @NotNull
    @Schema(description="协议(http,https)")
    private String protocol = "";

    /**
     * 域名
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="域名")
    private String domain = "";

    /**
     * 子目录
     */
    @Length(max = 50)
    @Nullable
    @Schema(description="子目录")
    private String subDir;

    /**
     * 主题
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="主题")
    private String theme = "default";

    /**
     * 手机端主题
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="手机端主题")
    private String mobileTheme = "default";

    /**
     * 每页条数
     */
    @NotNull
    @Schema(description="每页条数")
    private Short pageSize = 20;

    /**
     * LOGO
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="LOGO")
    private String logo;

    /**
     * SEO标题
     */
    @Length(max = 150)
    @Nullable
    @Schema(description="SEO标题")
    private String seoTitle;

    /**
     * SEO关键词
     */
    @Length(max = 150)
    @Nullable
    @Schema(description="SEO关键词")
    private String seoKeywords;

    /**
     * SEO描述
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="SEO描述")
    private String seoDescription;

    /**
     * 静态页文件
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="静态页文件")
    private String staticFile;

    /**
     * 手机端静态页文件
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="手机端静态页文件")
    private String mobileStaticFile;

    /**
     * 编辑器设置
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="编辑器设置")
    private String editorSettings;

    /**
     * 水印设置
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="水印设置")
    private String watermarkSettings;

    /**
     * 静态页设置
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="静态页设置")
    private String htmlSettings;

    /**
     * 留言板设置
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="留言板设置")
    private String messageBoardSettings;

    /**
     * 状态(0:正常,1:关闭)
     */
    @NotNull
    @Schema(description="状态(0:正常,1:关闭)")
    private Short status = 0;

    /**
     * 层级
     */
    @NotNull
    @Schema(description="层级")
    private Short depth = 1;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Integer order = 999999;

    /**
     * 浏览次数
     */
    @NotNull
    @Schema(description="浏览次数")
    private Long views = 0L;

    /**
     * 首页浏览次数
     */
    @NotNull
    @Schema(description="首页浏览次数")
    private Long selfViews = 0L;

    /**
     * 今日浏览次数
     */
    @NotNull
    @Schema(description="今日浏览次数")
    private Integer todayViews = 0;

    /**
     * 昨日浏览次数
     */
    @NotNull
    @Schema(description="昨日浏览次数")
    private Integer yesterdayViews = 0;

    /**
     * 最高浏览次数
     */
    @NotNull
    @Schema(description="最高浏览次数")
    private Integer maxViews = 0;

    /**
     * 最高浏览日期
     */
    @NotNull
    @Schema(description="最高浏览日期")
    private OffsetDateTime maxDate = OffsetDateTime.now();

    /**
     * 自定义主字段JSON
     */
    @Nullable
    @Schema(description="自定义主字段JSON")
    private String mainsJson;

    /**
     * 自定义大字段JSON
     */
    @Nullable
    @Schema(description="自定义大字段JSON")
    private String clobsJson;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Nullable
    public Long getParentId() {
        return parentId;
    }

    public void setParentId(@Nullable Long parentId) {
        this.parentId = parentId;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getModelId() {
        return modelId;
    }

    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    @Nullable
    public String getSubDir() {
        return subDir;
    }

    public void setSubDir(@Nullable String subDir) {
        this.subDir = subDir;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getMobileTheme() {
        return mobileTheme;
    }

    public void setMobileTheme(String mobileTheme) {
        this.mobileTheme = mobileTheme;
    }

    public Short getPageSize() {
        return pageSize;
    }

    public void setPageSize(Short pageSize) {
        this.pageSize = pageSize;
    }

    @Nullable
    public String getLogo() {
        return logo;
    }

    public void setLogo(@Nullable String logo) {
        this.logo = logo;
    }

    @Nullable
    public String getSeoTitle() {
        return seoTitle;
    }

    public void setSeoTitle(@Nullable String seoTitle) {
        this.seoTitle = seoTitle;
    }

    @Nullable
    public String getSeoKeywords() {
        return seoKeywords;
    }

    public void setSeoKeywords(@Nullable String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    @Nullable
    public String getSeoDescription() {
        return seoDescription;
    }

    public void setSeoDescription(@Nullable String seoDescription) {
        this.seoDescription = seoDescription;
    }

    @Nullable
    public String getStaticFile() {
        return staticFile;
    }

    public void setStaticFile(@Nullable String staticFile) {
        this.staticFile = staticFile;
    }

    @Nullable
    public String getMobileStaticFile() {
        return mobileStaticFile;
    }

    public void setMobileStaticFile(@Nullable String mobileStaticFile) {
        this.mobileStaticFile = mobileStaticFile;
    }

    @Nullable
    public String getEditorSettings() {
        return editorSettings;
    }

    public void setEditorSettings(@Nullable String editorSettings) {
        this.editorSettings = editorSettings;
    }

    @Nullable
    public String getWatermarkSettings() {
        return watermarkSettings;
    }

    public void setWatermarkSettings(@Nullable String watermarkSettings) {
        this.watermarkSettings = watermarkSettings;
    }

    @Nullable
    public String getHtmlSettings() {
        return htmlSettings;
    }

    public void setHtmlSettings(@Nullable String htmlSettings) {
        this.htmlSettings = htmlSettings;
    }

    @Nullable
    public String getMessageBoardSettings() {
        return messageBoardSettings;
    }

    public void setMessageBoardSettings(@Nullable String messageBoardSettings) {
        this.messageBoardSettings = messageBoardSettings;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Short getDepth() {
        return depth;
    }

    public void setDepth(Short depth) {
        this.depth = depth;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getViews() {
        return views;
    }

    public void setViews(Long views) {
        this.views = views;
    }

    public Long getSelfViews() {
        return selfViews;
    }

    public void setSelfViews(Long selfViews) {
        this.selfViews = selfViews;
    }

    public Integer getTodayViews() {
        return todayViews;
    }

    public void setTodayViews(Integer todayViews) {
        this.todayViews = todayViews;
    }

    public Integer getYesterdayViews() {
        return yesterdayViews;
    }

    public void setYesterdayViews(Integer yesterdayViews) {
        this.yesterdayViews = yesterdayViews;
    }

    public Integer getMaxViews() {
        return maxViews;
    }

    public void setMaxViews(Integer maxViews) {
        this.maxViews = maxViews;
    }

    public OffsetDateTime getMaxDate() {
        return maxDate;
    }

    public void setMaxDate(OffsetDateTime maxDate) {
        this.maxDate = maxDate;
    }

    @Nullable
    public String getMainsJson() {
        return mainsJson;
    }

    public void setMainsJson(@Nullable String mainsJson) {
        this.mainsJson = mainsJson;
    }

    @Nullable
    public String getClobsJson() {
        return clobsJson;
    }

    public void setClobsJson(@Nullable String clobsJson) {
        this.clobsJson = clobsJson;
    }
}