package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class CollectionBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "collection";

    /**
     * 采集ID
     */
    @NotNull
    @Schema(description="采集ID")
    private Long id = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 栏目ID
     */
    @NotNull
    @Schema(description="栏目ID")
    private Long channelId = 0L;

    /**
     * 用户ID
     */
    @NotNull
    @Schema(description="用户ID")
    private Long userId = 0L;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="名称")
    private String name = "";

    /**
     * 描述
     */
    @Length(max = 300)
    @Nullable
    @Schema(description="描述")
    private String description;

    /**
     * 字符集
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="字符集")
    private String charset = "UTF-8";

    /**
     * 用户代理
     */
    @Length(max = 255)
    @NotNull
    @Schema(description="用户代理")
    private String userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";

    /**
     * 最小间隔时间
     */
    @NotNull
    @Schema(description="最小间隔时间")
    private Integer intervalMin = 0;

    /**
     * 最大间隔时间
     */
    @NotNull
    @Schema(description="最大间隔时间")
    private Integer intervalMax = 0;

    /**
     * 列表地址
     */
    @Length(max = 2000)
    @NotNull
    @Schema(description="列表地址")
    private String listUrls = "";

    /**
     * 倒序采集
     */
    @NotNull
    @Schema(description="倒序采集")
    private Boolean listDesc = false;

    /**
     * 页码开始
     */
    @NotNull
    @Schema(description="页码开始")
    private Integer pageBegin = 2;

    /**
     * 页码结束
     */
    @NotNull
    @Schema(description="页码结束")
    private Integer pageEnd = 10;

    /**
     * 列表区域规则
     */
    @Length(max = 500)
    @Nullable
    @Schema(description="列表区域规则")
    private String listAreaPattern;

    /**
     * 列表区域是否正则
     */
    @NotNull
    @Schema(description="列表区域是否正则")
    private Boolean listAreaReg = false;

    /**
     * 条目区域规则
     */
    @Length(max = 500)
    @Nullable
    @Schema(description="条目区域规则")
    private String itemAreaPattern;

    /**
     * 条目区域是否正则
     */
    @NotNull
    @Schema(description="条目区域是否正则")
    private Boolean itemAreaReg = false;

    /**
     * 文章地址规则
     */
    @Length(max = 500)
    @NotNull
    @Schema(description="文章地址规则")
    private String itemUrlPattern = "";

    /**
     * 文章地址过滤
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="文章地址过滤")
    private String itemUrlFilter;

    /**
     * 文章地址是否正则
     */
    @NotNull
    @Schema(description="文章地址是否正则")
    private Boolean itemUrlReg = false;

    /**
     * 文章地址是否JS
     */
    @NotNull
    @Schema(description="文章地址是否JS")
    private Boolean itemUrlJs = false;

    /**
     * 是否自动提交
     */
    @NotNull
    @Schema(description="是否自动提交")
    private Boolean autoSubmit = true;

    /**
     * 是否允许重复标题
     */
    @NotNull
    @Schema(description="是否允许重复标题")
    private Boolean allowDuplicate = false;

    /**
     * 是否下载正文中的图片
     */
    @NotNull
    @Schema(description="是否下载正文中的图片")
    private Boolean downloadImage = true;

    /**
     * 当前采集页数
     */
    @NotNull
    @Schema(description="当前采集页数")
    private Integer currentPages = 0;

    /**
     * 当前采集条数
     */
    @NotNull
    @Schema(description="当前采集条数")
    private Integer currentItems = 0;

    /**
     * 当前采集成功数
     */
    @NotNull
    @Schema(description="当前采集成功数")
    private Integer successCount = 0;

    /**
     * 当前采集总数
     */
    @NotNull
    @Schema(description="当前采集总数")
    private Integer totalCount = 0;

    /**
     * 状态(0:未运行,1:运行中,2:暂停,3:完成,4:出错)
     */
    @NotNull
    @Schema(description="状态(0:未运行,1:运行中,2:暂停,3:完成,4:出错)")
    private Short status = 0;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Long order = 0L;

    /**
     * 当前错误信息
     */
    @Nullable
    @Schema(description="当前错误信息")
    private String errorInfo;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    public String getCharset() {
        return charset;
    }

    public void setCharset(String charset) {
        this.charset = charset;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    public Integer getIntervalMin() {
        return intervalMin;
    }

    public void setIntervalMin(Integer intervalMin) {
        this.intervalMin = intervalMin;
    }

    public Integer getIntervalMax() {
        return intervalMax;
    }

    public void setIntervalMax(Integer intervalMax) {
        this.intervalMax = intervalMax;
    }

    public String getListUrls() {
        return listUrls;
    }

    public void setListUrls(String listUrls) {
        this.listUrls = listUrls;
    }

    public Boolean getListDesc() {
        return listDesc;
    }

    public void setListDesc(Boolean listDesc) {
        this.listDesc = listDesc;
    }

    public Integer getPageBegin() {
        return pageBegin;
    }

    public void setPageBegin(Integer pageBegin) {
        this.pageBegin = pageBegin;
    }

    public Integer getPageEnd() {
        return pageEnd;
    }

    public void setPageEnd(Integer pageEnd) {
        this.pageEnd = pageEnd;
    }

    @Nullable
    public String getListAreaPattern() {
        return listAreaPattern;
    }

    public void setListAreaPattern(@Nullable String listAreaPattern) {
        this.listAreaPattern = listAreaPattern;
    }

    public Boolean getListAreaReg() {
        return listAreaReg;
    }

    public void setListAreaReg(Boolean listAreaReg) {
        this.listAreaReg = listAreaReg;
    }

    @Nullable
    public String getItemAreaPattern() {
        return itemAreaPattern;
    }

    public void setItemAreaPattern(@Nullable String itemAreaPattern) {
        this.itemAreaPattern = itemAreaPattern;
    }

    public Boolean getItemAreaReg() {
        return itemAreaReg;
    }

    public void setItemAreaReg(Boolean itemAreaReg) {
        this.itemAreaReg = itemAreaReg;
    }

    public String getItemUrlPattern() {
        return itemUrlPattern;
    }

    public void setItemUrlPattern(String itemUrlPattern) {
        this.itemUrlPattern = itemUrlPattern;
    }

    @Nullable
    public String getItemUrlFilter() {
        return itemUrlFilter;
    }

    public void setItemUrlFilter(@Nullable String itemUrlFilter) {
        this.itemUrlFilter = itemUrlFilter;
    }

    public Boolean getItemUrlReg() {
        return itemUrlReg;
    }

    public void setItemUrlReg(Boolean itemUrlReg) {
        this.itemUrlReg = itemUrlReg;
    }

    public Boolean getItemUrlJs() {
        return itemUrlJs;
    }

    public void setItemUrlJs(Boolean itemUrlJs) {
        this.itemUrlJs = itemUrlJs;
    }

    public Boolean getAutoSubmit() {
        return autoSubmit;
    }

    public void setAutoSubmit(Boolean autoSubmit) {
        this.autoSubmit = autoSubmit;
    }

    public Boolean getAllowDuplicate() {
        return allowDuplicate;
    }

    public void setAllowDuplicate(Boolean allowDuplicate) {
        this.allowDuplicate = allowDuplicate;
    }

    public Boolean getDownloadImage() {
        return downloadImage;
    }

    public void setDownloadImage(Boolean downloadImage) {
        this.downloadImage = downloadImage;
    }

    public Integer getCurrentPages() {
        return currentPages;
    }

    public void setCurrentPages(Integer currentPages) {
        this.currentPages = currentPages;
    }

    public Integer getCurrentItems() {
        return currentItems;
    }

    public void setCurrentItems(Integer currentItems) {
        this.currentItems = currentItems;
    }

    public Integer getSuccessCount() {
        return successCount;
    }

    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

    public Integer getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }

    @Nullable
    public String getErrorInfo() {
        return errorInfo;
    }

    public void setErrorInfo(@Nullable String errorInfo) {
        this.errorInfo = errorInfo;
    }
}