package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class CollectionFieldBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "collection_field";

    /**
     * 采集字段ID
     */
    @NotNull
    @Schema(description="采集字段ID")
    private Long id = 0L;

    /**
     * 采集ID
     */
    @NotNull
    @Schema(description="采集ID")
    private Long collectionId = 0L;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="名称")
    private String name = "";

    /**
     * 代码
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="代码")
    private String code = "";

    /**
     * 类型(1:系统字段,2:自定义字段)
     */
    @NotNull
    @Schema(description="类型(1:系统字段,2:自定义字段)")
    private Short type = 1;

    /**
     * 数据类型(1:文本,2:日期,11:图片,12:音频,13:视频,14:附件,21:图片集,22:附件集)
     */
    @NotNull
    @Schema(description="数据类型(1:文本,2:日期,11:图片,12:音频,13:视频,14:附件,21:图片集,22:附件集)")
    private Short dataType = 1;

    /**
     * 来源(1:详细页,2:列表页,3:固定值)
     */
    @NotNull
    @Schema(description="来源(1:详细页,2:列表页,3:固定值)")
    private Short source = 1;

    /**
     * 固定值
     */
    @Length(max = 300)
    @Nullable
    @Schema(description="固定值")
    private String staticValue;

    /**
     * 日期格式
     */
    @Length(max = 50)
    @Nullable
    @Schema(description="日期格式")
    private String dateFormat;

    /**
     * 区域规则
     */
    @Length(max = 500)
    @Nullable
    @Schema(description="区域规则")
    private String areaPattern;

    /**
     * 区域是否正则
     */
    @NotNull
    @Schema(description="区域是否正则")
    private Boolean areaReg = false;

    /**
     * 条目规则
     */
    @Length(max = 500)
    @Nullable
    @Schema(description="条目规则")
    private String itemPattern;

    /**
     * 条目过滤
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="条目过滤")
    private String itemFilter;

    /**
     * 条目是否正则
     */
    @NotNull
    @Schema(description="条目是否正则")
    private Boolean itemReg = false;

    /**
     * 条目是否JS
     */
    @NotNull
    @Schema(description="条目是否JS")
    private Boolean itemJs = false;

    /**
     * 数据URL
     */
    @Length(max = 255)
    @Nullable
    @Schema(description="数据URL")
    private String dataUrl;

    /**
     * 数据过滤
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="数据过滤")
    private String dataFilter;

    /**
     * 数据是否JS
     */
    @NotNull
    @Schema(description="数据是否JS")
    private Boolean dataJs = false;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Integer order = 0;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCollectionId() {
        return collectionId;
    }

    public void setCollectionId(Long collectionId) {
        this.collectionId = collectionId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Short getType() {
        return type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public Short getDataType() {
        return dataType;
    }

    public void setDataType(Short dataType) {
        this.dataType = dataType;
    }

    public Short getSource() {
        return source;
    }

    public void setSource(Short source) {
        this.source = source;
    }

    @Nullable
    public String getStaticValue() {
        return staticValue;
    }

    public void setStaticValue(@Nullable String staticValue) {
        this.staticValue = staticValue;
    }

    @Nullable
    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(@Nullable String dateFormat) {
        this.dateFormat = dateFormat;
    }

    @Nullable
    public String getAreaPattern() {
        return areaPattern;
    }

    public void setAreaPattern(@Nullable String areaPattern) {
        this.areaPattern = areaPattern;
    }

    public Boolean getAreaReg() {
        return areaReg;
    }

    public void setAreaReg(Boolean areaReg) {
        this.areaReg = areaReg;
    }

    @Nullable
    public String getItemPattern() {
        return itemPattern;
    }

    public void setItemPattern(@Nullable String itemPattern) {
        this.itemPattern = itemPattern;
    }

    @Nullable
    public String getItemFilter() {
        return itemFilter;
    }

    public void setItemFilter(@Nullable String itemFilter) {
        this.itemFilter = itemFilter;
    }

    public Boolean getItemReg() {
        return itemReg;
    }

    public void setItemReg(Boolean itemReg) {
        this.itemReg = itemReg;
    }

    public Boolean getItemJs() {
        return itemJs;
    }

    public void setItemJs(Boolean itemJs) {
        this.itemJs = itemJs;
    }

    @Nullable
    public String getDataUrl() {
        return dataUrl;
    }

    public void setDataUrl(@Nullable String dataUrl) {
        this.dataUrl = dataUrl;
    }

    @Nullable
    public String getDataFilter() {
        return dataFilter;
    }

    public void setDataFilter(@Nullable String dataFilter) {
        this.dataFilter = dataFilter;
    }

    public Boolean getDataJs() {
        return dataJs;
    }

    public void setDataJs(Boolean dataJs) {
        this.dataJs = dataJs;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }
}