package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class FormBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "form";

    /**
     * 表单ID
     */
    @NotNull
    @Schema(description="表单ID")
    private Long id = 0L;

    /**
     * 表单类型ID
     */
    @NotNull
    @Schema(description="表单类型ID")
    private Long typeId = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 组织ID
     */
    @NotNull
    @Schema(description="组织ID")
    private Long orgId = 0L;

    /**
     * 创建用户ID
     */
    @NotNull
    @Schema(description="创建用户ID")
    private Long userId = 0L;

    /**
     * 修改用户ID
     */
    @NotNull
    @Schema(description="修改用户ID")
    private Long modifiedUserId = 0L;

    /**
     * 流程实例ID
     */
    @Length(max = 64)
    @Nullable
    @Schema(description="流程实例ID")
    private String processInstanceId;

    /**
     * 退回原因
     */
    @Length(max = 300)
    @Nullable
    @Schema(description="退回原因")
    private String rejectReason;

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 修改日期
     */
    @NotNull
    @Schema(description="修改日期")
    private OffsetDateTime modified = OffsetDateTime.now();

    /**
     * IP地址
     */
    @Length(max = 45)
    @NotNull
    @Schema(description="IP地址")
    private String ip = "";

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Long order = 0L;

    /**
     * 状态(0:已审核,10:草稿,11:待审核,12:审核中,20:已删除,22:已退回)
     */
    @NotNull
    @Schema(description="状态(0:已审核,10:草稿,11:待审核,12:审核中,20:已删除,22:已退回)")
    private Short status = 0;

    /**
     * 自定义主字段
     */
    @Nullable
    @Schema(description="自定义主字段")
    private String mainsJson;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    @Nullable
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(@Nullable String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    @Nullable
    public String getRejectReason() {
        return rejectReason;
    }

    public void setRejectReason(@Nullable String rejectReason) {
        this.rejectReason = rejectReason;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public OffsetDateTime getModified() {
        return modified;
    }

    public void setModified(OffsetDateTime modified) {
        this.modified = modified;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    @Nullable
    public String getMainsJson() {
        return mainsJson;
    }

    public void setMainsJson(@Nullable String mainsJson) {
        this.mainsJson = mainsJson;
    }
}