package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class MessageBoardBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "message_board";

    /**
     * 留言ID
     */
    @NotNull
    @Schema(description="留言ID")
    private Long id = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 类别ID
     */
    @NotNull
    @Schema(description="类别ID")
    private Long typeId = 0L;

    /**
     * 留言用户ID
     */
    @NotNull
    @Schema(description="留言用户ID")
    private Long userId = 0L;

    /**
     * 回复用户ID
     */
    @Nullable
    @Schema(description="回复用户ID")
    private Long replyUserId;

    /**
     * 留言标题
     */
    @Length(max = 150)
    @NotNull
    @Schema(description="留言标题")
    private String title = "";

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 回复日期
     */
    @Nullable
    @Schema(description="回复日期")
    private OffsetDateTime replyDate;

    /**
     * 联系人
     */
    @Length(max = 30)
    @Nullable
    @Schema(description="联系人")
    private String contact;

    /**
     * 昵称
     */
    @Length(max = 30)
    @Nullable
    @Schema(description="昵称")
    private String nickname;

    /**
     * 电话号码
     */
    @Length(max = 50)
    @Nullable
    @Schema(description="电话号码")
    private String phone;

    /**
     * 电子邮箱
     */
    @Length(max = 50)
    @Nullable
    @Schema(description="电子邮箱")
    private String email;

    /**
     * 联系地址
     */
    @Length(max = 150)
    @Nullable
    @Schema(description="联系地址")
    private String address;

    /**
     * 是否公开
     */
    @NotNull
    @Schema(description="是否公开")
    private Boolean open = true;

    /**
     * IP地址
     */
    @Length(max = 45)
    @NotNull
    @Schema(description="IP地址")
    private String ip = "";

    /**
     * 是否回复
     */
    @NotNull
    @Schema(description="是否回复")
    private Boolean replied = false;

    /**
     * 是否推荐
     */
    @NotNull
    @Schema(description="是否推荐")
    private Boolean recommended = false;

    /**
     * 状态(0:已审核,1:未审核,2:已屏蔽)
     */
    @NotNull
    @Schema(description="状态(0:已审核,1:未审核,2:已屏蔽)")
    private Short status = 1;

    /**
     * 留言内容
     */
    @Nullable
    @Schema(description="留言内容")
    private String text;

    /**
     * 回复内容
     */
    @Nullable
    @Schema(description="回复内容")
    private String replyText;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Nullable
    public Long getReplyUserId() {
        return replyUserId;
    }

    public void setReplyUserId(@Nullable Long replyUserId) {
        this.replyUserId = replyUserId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    @Nullable
    public OffsetDateTime getReplyDate() {
        return replyDate;
    }

    public void setReplyDate(@Nullable OffsetDateTime replyDate) {
        this.replyDate = replyDate;
    }

    @Nullable
    public String getContact() {
        return contact;
    }

    public void setContact(@Nullable String contact) {
        this.contact = contact;
    }

    @Nullable
    public String getNickname() {
        return nickname;
    }

    public void setNickname(@Nullable String nickname) {
        this.nickname = nickname;
    }

    @Nullable
    public String getPhone() {
        return phone;
    }

    public void setPhone(@Nullable String phone) {
        this.phone = phone;
    }

    @Nullable
    public String getEmail() {
        return email;
    }

    public void setEmail(@Nullable String email) {
        this.email = email;
    }

    @Nullable
    public String getAddress() {
        return address;
    }

    public void setAddress(@Nullable String address) {
        this.address = address;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Boolean getReplied() {
        return replied;
    }

    public void setReplied(Boolean replied) {
        this.replied = replied;
    }

    public Boolean getRecommended() {
        return recommended;
    }

    public void setRecommended(Boolean recommended) {
        this.recommended = recommended;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    @Nullable
    public String getText() {
        return text;
    }

    public void setText(@Nullable String text) {
        this.text = text;
    }

    @Nullable
    public String getReplyText() {
        return replyText;
    }

    public void setReplyText(@Nullable String replyText) {
        this.replyText = replyText;
    }
}