package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SurveyBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "survey";

    /**
     * 问卷ID
     */
    @NotNull
    @Schema(description="问卷ID")
    private Long id = 0L;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Long siteId = 0L;

    /**
     * 标题
     */
    @Length(max = 1000)
    @NotNull
    @Schema(description="标题")
    private String title = "";

    /**
     * 描述
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="描述")
    private String description;

    /**
     * 开始日期
     */
    @Nullable
    @Schema(description="开始日期")
    private OffsetDateTime beginDate;

    /**
     * 结束日期
     */
    @Nullable
    @Schema(description="结束日期")
    private OffsetDateTime endDate;

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 模式(1:独立访客,2:独立IP,3:独立用户)
     */
    @NotNull
    @Schema(description="模式(1:独立访客,2:独立IP,3:独立用户)")
    private Short mode = 1;

    /**
     * 参与人次
     */
    @NotNull
    @Schema(description="参与人次")
    private Integer times = 0;

    /**
     * 重复问答间隔天数(0:不可重复问答)
     */
    @NotNull
    @Schema(description="重复问答间隔天数(0:不可重复问答)")
    private Integer interval = 0;

    /**
     * 是否启用
     */
    @NotNull
    @Schema(description="是否启用")
    private Boolean enabled = true;

    /**
     * 排列顺序
     */
    @NotNull
    @Schema(description="排列顺序")
    private Long order = 0L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @Nullable
    public OffsetDateTime getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(@Nullable OffsetDateTime beginDate) {
        this.beginDate = beginDate;
    }

    @Nullable
    public OffsetDateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(@Nullable OffsetDateTime endDate) {
        this.endDate = endDate;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public Short getMode() {
        return mode;
    }

    public void setMode(Short mode) {
        this.mode = mode;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public Integer getInterval() {
        return interval;
    }

    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }
}