package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SurveyOptionFeedbackBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "survey_option_feedback";

    /**
     * 主键ID
     */
    @NotNull
    @Schema(description="主键ID")
    private Integer id = 0;

    /**
     * 问卷选项ID
     */
    @NotNull
    @Schema(description="问卷选项ID")
    private Integer surveyOptionId = 0;

    /**
     * 问卷反馈ID
     */
    @NotNull
    @Schema(description="问卷反馈ID")
    private Integer surveyFeedbackId = 0;

    /**
     * 问卷ID
     */
    @NotNull
    @Schema(description="问卷ID")
    private Integer surveyId = 0;

    /**
     * 问卷条目ID
     */
    @NotNull
    @Schema(description="问卷条目ID")
    private Integer surveyItemId = 0;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSurveyOptionId() {
        return surveyOptionId;
    }

    public void setSurveyOptionId(Integer surveyOptionId) {
        this.surveyOptionId = surveyOptionId;
    }

    public Integer getSurveyFeedbackId() {
        return surveyFeedbackId;
    }

    public void setSurveyFeedbackId(Integer surveyFeedbackId) {
        this.surveyFeedbackId = surveyFeedbackId;
    }

    public Integer getSurveyId() {
        return surveyId;
    }

    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    public Integer getSurveyItemId() {
        return surveyItemId;
    }

    public void setSurveyItemId(Integer surveyItemId) {
        this.surveyItemId = surveyItemId;
    }
}