package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class SurveyItemBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "survey_item";

    /**
     * 问卷条目ID
     */
    @NotNull
    @Schema(description="问卷条目ID")
    private Integer id = 0;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Integer siteId = 0;

    /**
     * 问卷ID
     */
    @NotNull
    @Schema(description="问卷ID")
    private Integer surveyId = 0;

    /**
     * 标题
     */
    @Length(max = 1000)
    @NotNull
    @Schema(description="标题")
    private String title = "";

    /**
     * 排序
     */
    @NotNull
    @Schema(description="排序")
    private Integer order = 0;

    /**
     * 是否多选
     */
    @NotNull
    @Schema(description="是否多选")
    private Boolean multiple = false;

    /**
     * 是否问答
     */
    @NotNull
    @Schema(description="是否问答")
    private Boolean essay = false;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Integer getSurveyId() {
        return surveyId;
    }

    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Boolean getMultiple() {
        return multiple;
    }

    public void setMultiple(Boolean multiple) {
        this.multiple = multiple;
    }

    public Boolean getEssay() {
        return essay;
    }

    public void setEssay(Boolean essay) {
        this.essay = essay;
    }
}