package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class VoteBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "vote";

    /**
     * 投票ID
     */
    @NotNull
    @Schema(description="投票ID")
    private Integer id = 0;

    /**
     * 站点ID
     */
    @NotNull
    @Schema(description="站点ID")
    private Integer siteId = 0;

    /**
     * 标题
     */
    @Length(max = 1000)
    @NotNull
    @Schema(description="标题")
    private String title = "";

    /**
     * 描述
     */
    @Length(max = 1000)
    @Nullable
    @Schema(description="描述")
    private String description;

    /**
     * 开始日期
     */
    @Nullable
    @Schema(description="开始日期")
    private OffsetDateTime beginDate;

    /**
     * 结束日期
     */
    @Nullable
    @Schema(description="结束日期")
    private OffsetDateTime endDate;

    /**
     * 排序日期
     */
    @NotNull
    @Schema(description="排序日期")
    private OffsetDateTime orderDate = OffsetDateTime.now();

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * 重复投票间隔天数(0:不可重复投票)
     */
    @NotNull
    @Schema(description="重复投票间隔天数(0:不可重复投票)")
    private Integer interval = 0;

    /**
     * 参与人次
     */
    @NotNull
    @Schema(description="参与人次")
    private Integer times = 0;

    /**
     * 模式(1:独立访客,2:独立IP,3:独立用户)
     */
    @NotNull
    @Schema(description="模式(1:独立访客,2:独立IP,3:独立用户)")
    private Short mode = 1;

    /**
     * 是否多选
     */
    @NotNull
    @Schema(description="是否多选")
    private Boolean multiple = false;

    /**
     * 是否启用
     */
    @NotNull
    @Schema(description="是否启用")
    private Boolean enabled = true;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @Nullable
    public OffsetDateTime getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(@Nullable OffsetDateTime beginDate) {
        this.beginDate = beginDate;
    }

    @Nullable
    public OffsetDateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(@Nullable OffsetDateTime endDate) {
        this.endDate = endDate;
    }

    public OffsetDateTime getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(OffsetDateTime orderDate) {
        this.orderDate = orderDate;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public Integer getInterval() {
        return interval;
    }

    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public Short getMode() {
        return mode;
    }

    public void setMode(Short mode) {
        this.mode = mode;
    }

    public Boolean getMultiple() {
        return multiple;
    }

    public void setMultiple(Boolean multiple) {
        this.multiple = multiple;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}