package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class VoteOptionBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "vote_option";

    /**
     * 投票选项ID
     */
    @NotNull
    @Schema(description="投票选项ID")
    private Integer id = 0;

    /**
     * 投票ID
     */
    @NotNull
    @Schema(description="投票ID")
    private Integer voteId = 0;

    /**
     * 标题
     */
    @Length(max = 300)
    @NotNull
    @Schema(description="标题")
    private String title = "";

    /**
     * 得票数
     */
    @NotNull
    @Schema(description="得票数")
    private Integer count = 0;

    /**
     * 排序
     */
    @NotNull
    @Schema(description="排序")
    private Integer order = 0;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getVoteId() {
        return voteId;
    }

    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }
}