name: Publishing image to Docker Hub and GitHub Packages
on: [push]
#on:
#  push:
#    tags:
#      - v*
jobs:
  publishing-image-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ujcms/ujcms
      - run: echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'
      # - name: Build and push Docker image
      #   id: push
      #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true